# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a5cd0ca4b49cb42853503e8ba946e2f1c33b9ef1f48e3279b62f6c0c58fc878fbdaf5c9ad77b6ea2d5c69571c6578390daf707e7c0d9f29391527fe6e46117

test:
  secret_key_base: 4125ba169f014b603f4a10b838106d1d27b13232f2d6cfd9ed163e2a9e7be3771b83654213e9846fc012bb29e7569233212e4069d0ecc6ac28b6f305847d3390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
